# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('title', 'slug')]),
        ),
    ]
